version: 2
jobs:
  build_release:
    machine:
      image: art.sec.samsung.net/ci-docker/lws/starfish:latest
    environment:
      no_proxy: 168.219.241.169,168.219.245.245,168.219.244.109
    steps:
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh -
      - checkout
      - run: git submodule sync; git submodule update --init --recursive
      - run: ./configure --without-npm --without-bundled-v8 --without-v8-platform
             --without-inspector --without-node-code-cache --without-node-snapshot
             --with-intl none --shared-zlib --dest-os linux --dest-cpu x64
             --engine escargot --ninja
      - run: |
          gcc --version
          cmake --version
          ninja -v -C out/Release node
          du -h out/Release/node
      - run:
          name: Run Hello World
          command: out/Release/node test/message/hello_world.js
      # - run:
      #     name: Run node.js TCs
      #     command: |
      #       ln -sf out/Release/node node && ./lwnode/code/escargotshim/test/jstester/jstester.py --process 2
  test:
    machine:
      image: art.sec.samsung.net/ci-docker/lws/starfish:latest
    environment:
      no_proxy: 168.219.241.169,168.219.245.245,168.219.244.109
    steps:
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh -
      - checkout
      - run: git submodule sync; git submodule update --init --recursive
      - run: ./lwnode/build-cctest.sh
      - run: ./out/cctest/out/Debug/cctest

workflows:
    version: 2
    build_release:
      jobs:
        - build_release
    test:
      jobs:
        - test
