version: 2

# Configuration
config: &config
  machine:
    image: art.sec.samsung.net/ci-docker/lws/starfish:latest
  environment:
    no_proxy: 168.219.241.169,168.219.245.245,168.219.244.109

set_proxy: &set_proxy
  run:
    name: Set proxy
    command: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh

# Submodule
check_submodule_status: &check_submodule_status
  run:
    name: Check submodule status
    command: git submodule status | tee ~/submodule-status

restore_submodule_cache: &restore_submodule_cache
  restore_cache:
    name: Restoring cached submodules
    key: v2-submodules-{{ checksum "~/submodule-status" }}

save_submodule_cache: &save_submodule_cache
  save_cache:
    name: Caching submodules
    paths:
      - .git/modules
      - lwnode/code/escargotshim/deps/escargot
    key: v2-submodules-{{ checksum "~/submodule-status" }}

jobs:
  build_release:
    <<: *config
    steps:
      - *set_proxy
      - checkout
      - run:
          name: Check tidy
          command: ./lwnode/tools/check_tidy.py
      - *check_submodule_status
      - *restore_submodule_cache
      - run: git submodule update --init --recursive
      - *save_submodule_cache
      - run:
          name: Environment Information
          command: gcc --version; cmake --version; python --version
      - run:
          name: Build
          command: |
            ./configure --without-npm --without-bundled-v8 \
            --without-inspector --without-node-code-cache --without-node-snapshot \
            --with-intl none --shared-zlib --dest-os linux --dest-cpu x64 \
            --engine escargot --ninja
            ninja -v -C out/linux/Release lwnode
      - run:
          name: Run basic test
          command: |
            out/linux/Release/lwnode test/message/hello_world.js
            out/linux/Release/lwnode lwnode/test/node/test/memory/test-memory-basic.js
            mkdir -p ~/artifacts
            cp /tmp/*.csv ~/artifacts/.
      - run:
          name: Run node.js TCs (test.py)
          command: tools/test.py -J -p dots --report --time
                  --timeout 240 --repeat 1
                  --skip-tests=$(paste -sd, lwnode/code/escargotshim/test/jstester/skip_list.txt)
                  test/parallel
      - store_artifacts:
          path: ~/artifacts
          destination: artifacts

  node_test_jstester:
    <<: *config
    steps:
      - run:
          name: Run node.js TCs
          command: |
            ln -sf out/Release/lwnode node
            lwnode/code/escargotshim/test/jstester/jstester.py --process 8

  cctest:
    <<: *config
    steps:
      - checkout
      - *check_submodule_status
      - *restore_submodule_cache
      - run: git submodule update --init --recursive
      - *save_submodule_cache
      - run: lwnode/build-cctest.sh
      - run: out/cctest/out/Debug/cctest

  build_tizen_6.5:
    <<: *config
    steps:
      - checkout
      - *check_submodule_status
      - *restore_submodule_cache
      - run: git submodule update --init --recursive
      - *save_submodule_cache
      - run:
          name: Build RPMs
          command: |
            gbs -c .circleci/gbs.conf build -A armv7l -P profile.t65std --include-all --incremental
      - run:
          name: Store artifacts
          command: |
            mkdir -p ~/artifacts
            cp ~/GBS-ROOT/t65std/local/repos/t65std/armv7l/RPMS/*.rpm ~/artifacts
      - store_artifacts:
          path: ~/artifacts
          destination: artifacts

workflows:
    version: 2
    verify_node:
      jobs:
        - build_release
    verify_cctest:
      jobs:
        - cctest
    verify_build:
      jobs:
        - build_tizen_6.5
