name: test_tizen_6.5

on:
  push:
    branches:
      - v14
      - v14.gh-action

env:
  NODE_VERSION: v14.14.0

jobs:
  build:
    runs-on: [self-hosted]
    timeout-minutes: 10
    outputs:
      hash: ${{ steps.vars.outputs.hash }}
    steps:
      - name: Check tools
        run: |
          /usr/bin/tsp
      - name: Checkout source
        uses: CODE-Actions/checkout@v2
        with:
          submodules: recursive
      - name: Declare variables
        id: vars
        run: |
          echo "::set-output name=hash::$(git log -1 --format=%h)"
      - name: Build RPMs
        run: |
          /usr/bin/tsp -nf /usr/bin/gbs -c .circleci/gbs.conf \
          build -B ~/GBS-ROOT/lwnode -A armv7l \
          --include-all --incremental -P profile.t65std \
          --define 'lib_type static'
      - name: Post build tasks
        run: |
          lwnode/tools/actions/post-build-task.sh
          node /home/github/tools/build-info.mjs rpm
      - name: Copy the outputs
        env:
          TARGET_PATH: /home/tv/github
        run: |
          mkdir -p $TARGET_PATH/bin/${{ steps.vars.outputs.hash }}
          cp -vr rpm/* $TARGET_PATH/bin/${{ steps.vars.outputs.hash }}
  test:
    needs: build
    runs-on: [self-hosted]
    timeout-minutes: 10
    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run test on target
        env:
          HASH: ${{ needs.build.outputs.hash }}
          HOST_ROOT_PATH: /mnt/rat2/github
        run: |
          cd /home/github/remote-job-runner
          /usr/bin/tsp -nf npm start
