env:
  node: true
  es6: true

rules:
  camelcase:
    - error
    - properties: 'never'
      ignoreDestructuring: true
      allow: ['child_process']
  comma-dangle:
    - error
    - arrays: 'always-multiline'
      objects: 'only-multiline'
      imports: 'only-multiline'
      exports: 'only-multiline'
  no-unused-vars: [error, { args: 'after-used' }]
  prefer-arrow-callback: error
  no-var: error
