name: Build Api

on:
  push:
    branches:
    - v14

jobs:
  build:
    runs-on: [ code-default ]
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: CODE-Actions/checkout@v2
        with:
          submodule: true
      - name: Generate Api
        run: |
          sudo apt -y install doxygen graphviz
          doxygen docs/Doxyfile
          cp -fr docs/api /tmp
      - name: Checkout Api branch
        uses: CODE-Actions/checkout@v2
        with:
          ref: gh-pages
      - name: Check for modified files
        id: git-check
        run: |
          cp -fr /tmp/api docs
          echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Publish Api
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Ryan Hyun Choi'
          git config --global user.email 'ryan.choi@samsung.com'
          git add -A
          git commit -m '[auto commit] Update doc'
          git push
