name: Close stalled issues and PRs
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-close: 30
        stale-pr-label: stalled
        stale-issue-label: stalled
        close-issue-message: Closing this because it has stalled. Feel free to reopen if this issue is still relevant, or to ping the collaborator who labelled it stalled if you have any questions.
        close-pr-message: Closing this because it has stalled. Feel free to reopen if this PR is still relevant, or to ping the collaborator who labelled it stalled if you have any questions.
        # used to filter issues to check whether or not should be closed, avoids hitting maximum operations allowed if needing to paginate through all open issues
        only-labels: stalled
        # max requests it will send per run to the GitHub API before it deliberately exits to avoid hitting API rate limits
        operations-per-run: 500
        # deactivates automatic removal of stalled label if issue gets any activity
        remove-stale-when-updated: false
        # deactivates automatic stale labelling as we prefer to do that manually
        days-before-stale: -1
