name: misc

on:
  pull_request:
  push:
    branches:
      - master
      - v[0-9]+.x-staging
      - v[0-9]+.x

env:
  NODE_VERSION: 12.x

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: NODE=$(which node) make doc-only
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: out/doc
      - name: Check links
        run: node tools/doc/checkLinks.js .
