name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: [ code-default ]
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
